# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - group: webrtc

pool:
  vmImage: 'ubuntu-22.04'

jobs: 
- job: android_build
  timeoutInMinutes: 0
  steps:
    - script: |
        echo Seeting up depot_tools
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      displayName: 'Setup'
    
    - script: |
        echo Syncing sources
        set -ex
        export PATH=$PATH:${PWD}/depot_tools
        fetch --nohooks webrtc_android
        gclient sync
        cd src 
        ./build/install-build-deps.sh
        git checkout branch-heads/$(android_branch)
      displayName: 'Sync sources'

    - script: |
         echo Building!
         set -ex
         export PATH=$PATH:${PWD}/depot_tools
         cd src
         ./tools_webrtc/android/build_aar.py
      displayName: 'Building'

    - task: CopyFiles@2
      displayName: 'Copy aar library'
      inputs:
        Contents: '*.aar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'WebRtc'
        publishLocation: 'Container'
