# .github/workflows/build-webrtc.yml
name: Build Android WebRTC

on:
  workflow_dispatch:
    inputs:
      webrtc_branch:
        description: 'WebRTC branch to build (e.g. branch-heads/5860 or main)'
        required: true
        default: 'main'
        
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /opt/hostedtoolcache
        sudo docker system prune -af || true
        df -h

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 git openjdk-11-jdk pkg-config libnss3 gnupg flex bison gperf build-essential zip curl zlib1g-dev

    - name: Clone depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$PWD/depot_tools" >> $GITHUB_PATH

    - name: Fetch WebRTC Android source
      run: |
        mkdir webrtc && cd webrtc
        fetch --nohooks webrtc_android
        cd src
        ./build/install-build-deps.sh
        gclient sync

    - name: Checkout selected WebRTC branch
      run: |
        cd webrtc/src
        git fetch origin
        git checkout "${{ github.event.inputs.webrtc_branch }}"
        gclient sync

    - name: Build libwebrtc.aar
      run: |
        cd webrtc/src
        python3 tools_webrtc/android/build_aar.py

    - name: Rename and upload artifact
      run: |
        cd webrtc/src
        SHORT_HASH=$(git rev-parse --short HEAD)
        VERSION_TAG=$(echo "${{ github.event.inputs.webrtc_branch }}" | sed 's/\//-/g')
        mv libwebrtc.aar libwebrtc-${VERSION_TAG}-${SHORT_HASH}.aar
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: libwebrtc-${{ github.event.inputs.webrtc_branch }}
        path: webrtc/src/libwebrtc-*.aar
