# .github/workflows/build-webrtc.yml
name: Build Android WebRTC

on:
  # allows manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /opt/hostedtoolcache
        sudo docker system prune -af || true
        df -h

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 git openjdk-11-jdk pkg-config libnss3 gnupg flex bison gperf build-essential zip curl zlib1g-dev

    - name: Clone depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$PWD/depot_tools" >> $GITHUB_PATH

    - name: Fetch WebRTC Android source
      run: |
        mkdir webrtc && cd webrtc
        fetch --nohooks webrtc_android
        cd src
        ./build/install-build-deps.sh
        gclient sync

    - name: Build WebRTC AAR
      run: |
        cd webrtc/src
        python3 tools_webrtc/android/build_aar.py

    - name: Get WebRTC version
      id: get_version
      run: |
        cd webrtc_android/src
        VERSION=$(python3 tools_webrtc/version/version.py | head -1)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Rename libwebrtc.aar with version
      run: |
        cd webrtc_android/src
        mv libwebrtc.aar libwebrtc-${{ steps.get_version.outputs.version }}.aar

    - name: Upload built AAR
      uses: actions/upload-artifact@v4
      with:
        name: libwebrtc-${{ steps.get_version.outputs.version }}
        path: webrtc_android/src/libwebrtc-${{ steps.get_version.outputs.version }}.aar
